### ISSUE TITLE
Using the Legacy Font Provider mod together with the Hardcore Ender Expansion mod results in the game freezing

### ISSUE THREAD

**Issue by Omgise** [Yukkuritaku/Legacy-Font-Provider#2]
[fml-client-latest.log](https://github.com/user-attachments/files/18138678/fml-client-latest.log)

https://github.com/user-attachments/assets/f558ac43-9501-4ecf-9060-a5a2d73b8332

**Comment by Omgise** [comment]
@Yukkuritaku Could you fix the compatibility with Hardcore Ender Expansion? Here is its source code: https://github.com/GTNewHorizons/Hardcore-Ender-Expansion.

**Comment by Omgise** [comment]
Maybe it is caused by this function of Hardcore Ender Expansion?
```
# Special text rendering mode for Ender Compendium, smooths out aliasing in Large GUI scale.
I:compendiumSmoothText=0
```

**Comment by Yukkuritaku** [comment]
自分でも似たような現象が確認できました(自分の場合はフリーズせず、ゲームがめちゃくちゃ重くなる感じになりました)
ただ、今Releaseにあるのってめちゃくちゃ古いバージョンで、masterブランチの最新のやつをまだリリースしてないんですよね
そっちだと重くなる現象は無かったので(多分)、後で公開します

**Comment by Omgise** [comment]
ありがとう！

**Comment by Omgise** [comment]
先ほど `legacyfontprovider-1.0.0-master.5+2d8106f544.jar` というこのバージョンを試してみたけど、ゲームはやはりクラッシュした
これはこのモッドのソースコードです：https://github.com/kappa-maintainer/ModernSplash


![image](https://github.com/user-attachments/assets/387e0f73-1ff1-4348-9f09-8a1ddae615c1)
[crash-2024-12-15_13.03.49-client.txt](https://github.com/user-attachments/files/18138925/crash-2024-12-15_13.03.49-client.txt)

[fml-client-latest.log](https://github.com/user-attachments/files/18138927/fml-client-latest.log)

**Comment by Omgise** [comment]
私は先ほど IDEA であなたのモッドを構築してテストしました

**Comment by Yukkuritaku** [comment]
多分このコミットで直るはずです

**Comment by Omgise** [comment]
ゲームはクラッシュしませんでしたが、レンダリングが奇妙に見えます
[fml-client-latest.log](https://github.com/user-attachments/files/18139115/fml-client-latest.log)


https://github.com/user-attachments/assets/82420f85-3310-4cc8-97b5-0c2a07e83046

**Comment by Yukkuritaku** [comment]
modの量が多くて再現性が難しいかもです...
どのmodと競合してるかとかわかりますか？

**Comment by Omgise** [comment]
私は先ほど、Modern Splash をインストールしていないとゲームがクラッシュすることも発見しました。後で Modern Splash をインストールして、その画像のレンダリングエラーを再現できるかどうか試してみます
[crash-2024-12-15_14.49.09-client.txt](https://github.com/user-attachments/files/18139222/crash-2024-12-15_14.49.09-client.txt)
[latest.log](https://github.com/user-attachments/files/18139223/latest.log)


![image](https://github.com/user-attachments/assets/c43c7d1d-a2b9-466e-9c20-13ebfdaea9d6)

**Comment by Omgise** [comment]
私は問題がどこにあるのかを発見しました。このテクスチャパックが原因です：https://modrinth.com/resourcepack/modernity/version/f1-3.10.2

**Comment by Omgise** [comment]
おおよそこれらのフォントのテクスチャが原因で起こった問題です
![image](https://github.com/user-attachments/assets/5f00c4ff-725a-4c75-95df-1320be377a19)

**Comment by Omgise** [comment]
このテクスチャパックとの衝突の問題は解決できますか？

**Comment by Omgise** [comment]
それとも、私はこれらのフォントのテクスチャを削除すべきでしょうか

**Comment by Yukkuritaku** [comment]
今コミットしたやつを使えば直ったりしますかね...?
Modern Splashを使わないと落ちてしまうのもこのコミットで直ってるはずです

**Comment by Omgise** [comment]
はい、あのModern Splash とメインインターフェースのメニューフォントのレンダリングの問題はあなたが直してくれました。残りはたった一つの Hardcore Ender Expansion のレンダリングの問題だけです。少しお待ちください。私はビデオを録画して展示します。お疲れ様でした 😊
![image](https://github.com/user-attachments/assets/f3d61881-f6e6-441e-b287-40582cb98846)

**Comment by Omgise** [comment]
私はよく調べましたが、問題は見つかりませんでした。本当にあなたのお手伝いに感謝します
